// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZLTest.proto

package com.zl.third.brother.utils.netty.protobuf;

public final class ZLTest {
  private ZLTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code E_ALL_TEST}
   */
  public enum E_ALL_TEST
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL_TEST_ONE = 0;</code>
     */
    ALL_TEST_ONE(0),
    /**
     * <pre>
     * </pre>
     *
     * <code>ALL_TEST_TWO = 1;</code>
     */
    ALL_TEST_TWO(1),
    /**
     * <pre>
     * </pre>
     *
     * <code>ALL_TEST_THREE = 2;</code>
     */
    ALL_TEST_THREE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ALL_TEST_ONE = 0;</code>
     */
    public static final int ALL_TEST_ONE_VALUE = 0;
    /**
     * <pre>
     * </pre>
     *
     * <code>ALL_TEST_TWO = 1;</code>
     */
    public static final int ALL_TEST_TWO_VALUE = 1;
    /**
     * <pre>
     * </pre>
     *
     * <code>ALL_TEST_THREE = 2;</code>
     */
    public static final int ALL_TEST_THREE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static E_ALL_TEST valueOf(int value) {
      return forNumber(value);
    }

    public static E_ALL_TEST forNumber(int value) {
      switch (value) {
        case 0: return ALL_TEST_ONE;
        case 1: return ALL_TEST_TWO;
        case 2: return ALL_TEST_THREE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<E_ALL_TEST>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        E_ALL_TEST> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<E_ALL_TEST>() {
            public E_ALL_TEST findValueByNumber(int number) {
              return E_ALL_TEST.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ZLTest.getDescriptor().getEnumTypes().get(0);
    }

    private static final E_ALL_TEST[] VALUES = values();

    public static E_ALL_TEST valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private E_ALL_TEST(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:E_ALL_TEST)
  }

  public interface C2S_GetUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_GetUserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>string content = 2;</code>
     */
    String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.TsetInfo info = 3;</code>
     */
    boolean hasInfo();
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    ZLBaseTest.TsetInfo getInfo();
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    java.util.List<AllInfo>
        getAllInfoList();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    AllInfo getAllInfo(int index);
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    int getAllInfoCount();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    java.util.List<? extends AllInfoOrBuilder>
        getAllInfoOrBuilderList();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    AllInfoOrBuilder getAllInfoOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code C2S_GetUserInfo}
   */
  public  static final class C2S_GetUserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2S_GetUserInfo)
      C2S_GetUserInfoOrBuilder {
    // Use C2S_GetUserInfo.newBuilder() to construct.
    private C2S_GetUserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_GetUserInfo() {
      userId_ = 0;
      content_ = "";
      allInfo_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private C2S_GetUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 26: {
              ZLBaseTest.TsetInfo.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(ZLBaseTest.TsetInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                allInfo_ = new java.util.ArrayList<AllInfo>();
                mutable_bitField0_ |= 0x00000008;
              }
              allInfo_.add(
                  input.readMessage(AllInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ZLTest.internal_static_C2S_GetUserInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ZLTest.internal_static_C2S_GetUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              C2S_GetUserInfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFO_FIELD_NUMBER = 3;
    private ZLBaseTest.TsetInfo info_;
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public ZLBaseTest.TsetInfo getInfo() {
      return info_ == null ? ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
    }
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    public static final int ALLINFO_FIELD_NUMBER = 4;
    private java.util.List<AllInfo> allInfo_;
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public java.util.List<AllInfo> getAllInfoList() {
      return allInfo_;
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public java.util.List<? extends AllInfoOrBuilder>
        getAllInfoOrBuilderList() {
      return allInfo_;
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public int getAllInfoCount() {
      return allInfo_.size();
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public AllInfo getAllInfo(int index) {
      return allInfo_.get(index);
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public AllInfoOrBuilder getAllInfoOrBuilder(
        int index) {
      return allInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (info_ != null) {
        output.writeMessage(3, getInfo());
      }
      for (int i = 0; i < allInfo_.size(); i++) {
        output.writeMessage(4, allInfo_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getInfo());
      }
      for (int i = 0; i < allInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, allInfo_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof C2S_GetUserInfo)) {
        return super.equals(obj);
      }
      C2S_GetUserInfo other = (C2S_GetUserInfo) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && getAllInfoList()
          .equals(other.getAllInfoList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (getAllInfoCount() > 0) {
        hash = (37 * hash) + ALLINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAllInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static C2S_GetUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C2S_GetUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C2S_GetUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static C2S_GetUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static C2S_GetUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C2S_GetUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static C2S_GetUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static C2S_GetUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static C2S_GetUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static C2S_GetUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(C2S_GetUserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_GetUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_GetUserInfo)
        C2S_GetUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ZLTest.internal_static_C2S_GetUserInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ZLTest.internal_static_C2S_GetUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                C2S_GetUserInfo.class, Builder.class);
      }

      // Construct using com.zl.third.brother.utils.netty.protobuf.ZLTest.C2S_GetUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0;

        content_ = "";

        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ZLTest.internal_static_C2S_GetUserInfo_descriptor;
      }

      public C2S_GetUserInfo getDefaultInstanceForType() {
        return C2S_GetUserInfo.getDefaultInstance();
      }

      public C2S_GetUserInfo build() {
        C2S_GetUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public C2S_GetUserInfo buildPartial() {
        C2S_GetUserInfo result = new C2S_GetUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.userId_ = userId_;
        result.content_ = content_;
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (allInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.allInfo_ = allInfo_;
        } else {
          result.allInfo_ = allInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof C2S_GetUserInfo) {
          return mergeFrom((C2S_GetUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(C2S_GetUserInfo other) {
        if (other == C2S_GetUserInfo.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (allInfoBuilder_ == null) {
          if (!other.allInfo_.isEmpty()) {
            if (allInfo_.isEmpty()) {
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAllInfoIsMutable();
              allInfo_.addAll(other.allInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.allInfo_.isEmpty()) {
            if (allInfoBuilder_.isEmpty()) {
              allInfoBuilder_.dispose();
              allInfoBuilder_ = null;
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              allInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllInfoFieldBuilder() : null;
            } else {
              allInfoBuilder_.addAllMessages(other.allInfo_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        C2S_GetUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (C2S_GetUserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *id
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private ZLBaseTest.TsetInfo info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder> infoBuilder_;
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder setInfo(ZLBaseTest.TsetInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder setInfo(
          ZLBaseTest.TsetInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder mergeInfo(ZLBaseTest.TsetInfo value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              ZLBaseTest.TsetInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfo.Builder getInfoBuilder() {
        
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
        }
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private java.util.List<AllInfo> allInfo_ =
        java.util.Collections.emptyList();
      private void ensureAllInfoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          allInfo_ = new java.util.ArrayList<AllInfo>(allInfo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AllInfo, AllInfo.Builder, AllInfoOrBuilder> allInfoBuilder_;

      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<AllInfo> getAllInfoList() {
        if (allInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allInfo_);
        } else {
          return allInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public int getAllInfoCount() {
        if (allInfoBuilder_ == null) {
          return allInfo_.size();
        } else {
          return allInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo getAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);
        } else {
          return allInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder setAllInfo(
          int index, AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.set(index, value);
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder setAllInfo(
          int index, AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          int index, AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(index, value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          int index, AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllAllInfo(
          Iterable<? extends AllInfo> values) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allInfo_);
          onChanged();
        } else {
          allInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder clearAllInfo() {
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder removeAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.remove(index);
          onChanged();
        } else {
          allInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder getAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfoOrBuilder getAllInfoOrBuilder(
          int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);  } else {
          return allInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<? extends AllInfoOrBuilder>
           getAllInfoOrBuilderList() {
        if (allInfoBuilder_ != null) {
          return allInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allInfo_);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder addAllInfoBuilder() {
        return getAllInfoFieldBuilder().addBuilder(
            AllInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder addAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().addBuilder(
            index, AllInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<AllInfo.Builder>
           getAllInfoBuilderList() {
        return getAllInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AllInfo, AllInfo.Builder, AllInfoOrBuilder>
          getAllInfoFieldBuilder() {
        if (allInfoBuilder_ == null) {
          allInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AllInfo, AllInfo.Builder, AllInfoOrBuilder>(
                  allInfo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          allInfo_ = null;
        }
        return allInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:C2S_GetUserInfo)
    }

    // @@protoc_insertion_point(class_scope:C2S_GetUserInfo)
    private static final C2S_GetUserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new C2S_GetUserInfo();
    }

    public static C2S_GetUserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2S_GetUserInfo>
        PARSER = new com.google.protobuf.AbstractParser<C2S_GetUserInfo>() {
      public C2S_GetUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_GetUserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_GetUserInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<C2S_GetUserInfo> getParserForType() {
      return PARSER;
    }

    public C2S_GetUserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2C_GetUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:S2C_GetUserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>.TsetInfo info = 3;</code>
     */
    boolean hasInfo();
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    ZLBaseTest.TsetInfo getInfo();
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    java.util.List<AllInfo>
        getAllInfoList();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    AllInfo getAllInfo(int index);
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    int getAllInfoCount();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    java.util.List<? extends AllInfoOrBuilder>
        getAllInfoOrBuilderList();
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    AllInfoOrBuilder getAllInfoOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code S2C_GetUserInfo}
   */
  public  static final class S2C_GetUserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:S2C_GetUserInfo)
      S2C_GetUserInfoOrBuilder {
    // Use S2C_GetUserInfo.newBuilder() to construct.
    private S2C_GetUserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_GetUserInfo() {
      name_ = "";
      age_ = 0;
      allInfo_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private S2C_GetUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              ZLBaseTest.TsetInfo.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(ZLBaseTest.TsetInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                allInfo_ = new java.util.ArrayList<AllInfo>();
                mutable_bitField0_ |= 0x00000008;
              }
              allInfo_.add(
                  input.readMessage(AllInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ZLTest.internal_static_S2C_GetUserInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ZLTest.internal_static_S2C_GetUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S2C_GetUserInfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int INFO_FIELD_NUMBER = 3;
    private ZLBaseTest.TsetInfo info_;
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public ZLBaseTest.TsetInfo getInfo() {
      return info_ == null ? ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
    }
    /**
     * <code>.TsetInfo info = 3;</code>
     */
    public ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    public static final int ALLINFO_FIELD_NUMBER = 4;
    private java.util.List<AllInfo> allInfo_;
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public java.util.List<AllInfo> getAllInfoList() {
      return allInfo_;
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public java.util.List<? extends AllInfoOrBuilder>
        getAllInfoOrBuilderList() {
      return allInfo_;
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public int getAllInfoCount() {
      return allInfo_.size();
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public AllInfo getAllInfo(int index) {
      return allInfo_.get(index);
    }
    /**
     * <code>repeated .AllInfo allInfo = 4;</code>
     */
    public AllInfoOrBuilder getAllInfoOrBuilder(
        int index) {
      return allInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (info_ != null) {
        output.writeMessage(3, getInfo());
      }
      for (int i = 0; i < allInfo_.size(); i++) {
        output.writeMessage(4, allInfo_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getInfo());
      }
      for (int i = 0; i < allInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, allInfo_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof S2C_GetUserInfo)) {
        return super.equals(obj);
      }
      S2C_GetUserInfo other = (S2C_GetUserInfo) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && getAllInfoList()
          .equals(other.getAllInfoList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (getAllInfoCount() > 0) {
        hash = (37 * hash) + ALLINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAllInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static S2C_GetUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S2C_GetUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S2C_GetUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S2C_GetUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S2C_GetUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S2C_GetUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static S2C_GetUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static S2C_GetUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static S2C_GetUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S2C_GetUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(S2C_GetUserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_GetUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:S2C_GetUserInfo)
        S2C_GetUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ZLTest.internal_static_S2C_GetUserInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ZLTest.internal_static_S2C_GetUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                S2C_GetUserInfo.class, Builder.class);
      }

      // Construct using com.zl.third.brother.utils.netty.protobuf.ZLTest.S2C_GetUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ZLTest.internal_static_S2C_GetUserInfo_descriptor;
      }

      public S2C_GetUserInfo getDefaultInstanceForType() {
        return S2C_GetUserInfo.getDefaultInstance();
      }

      public S2C_GetUserInfo build() {
        S2C_GetUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public S2C_GetUserInfo buildPartial() {
        S2C_GetUserInfo result = new S2C_GetUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (allInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.allInfo_ = allInfo_;
        } else {
          result.allInfo_ = allInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof S2C_GetUserInfo) {
          return mergeFrom((S2C_GetUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(S2C_GetUserInfo other) {
        if (other == S2C_GetUserInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (allInfoBuilder_ == null) {
          if (!other.allInfo_.isEmpty()) {
            if (allInfo_.isEmpty()) {
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAllInfoIsMutable();
              allInfo_.addAll(other.allInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.allInfo_.isEmpty()) {
            if (allInfoBuilder_.isEmpty()) {
              allInfoBuilder_.dispose();
              allInfoBuilder_ = null;
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              allInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllInfoFieldBuilder() : null;
            } else {
              allInfoBuilder_.addAllMessages(other.allInfo_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        S2C_GetUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (S2C_GetUserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private ZLBaseTest.TsetInfo info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder> infoBuilder_;
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder setInfo(ZLBaseTest.TsetInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder setInfo(
          ZLBaseTest.TsetInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder mergeInfo(ZLBaseTest.TsetInfo value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              ZLBaseTest.TsetInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfo.Builder getInfoBuilder() {
        
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      public ZLBaseTest.TsetInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              ZLBaseTest.TsetInfo.getDefaultInstance() : info_;
        }
      }
      /**
       * <code>.TsetInfo info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ZLBaseTest.TsetInfo, ZLBaseTest.TsetInfo.Builder, ZLBaseTest.TsetInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private java.util.List<AllInfo> allInfo_ =
        java.util.Collections.emptyList();
      private void ensureAllInfoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          allInfo_ = new java.util.ArrayList<AllInfo>(allInfo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AllInfo, AllInfo.Builder, AllInfoOrBuilder> allInfoBuilder_;

      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<AllInfo> getAllInfoList() {
        if (allInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allInfo_);
        } else {
          return allInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public int getAllInfoCount() {
        if (allInfoBuilder_ == null) {
          return allInfo_.size();
        } else {
          return allInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo getAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);
        } else {
          return allInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder setAllInfo(
          int index, AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.set(index, value);
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder setAllInfo(
          int index, AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          int index, AllInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(index, value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllInfo(
          int index, AllInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder addAllAllInfo(
          Iterable<? extends AllInfo> values) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allInfo_);
          onChanged();
        } else {
          allInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder clearAllInfo() {
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public Builder removeAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.remove(index);
          onChanged();
        } else {
          allInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder getAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfoOrBuilder getAllInfoOrBuilder(
          int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);  } else {
          return allInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<? extends AllInfoOrBuilder>
           getAllInfoOrBuilderList() {
        if (allInfoBuilder_ != null) {
          return allInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allInfo_);
        }
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder addAllInfoBuilder() {
        return getAllInfoFieldBuilder().addBuilder(
            AllInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public AllInfo.Builder addAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().addBuilder(
            index, AllInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AllInfo allInfo = 4;</code>
       */
      public java.util.List<AllInfo.Builder>
           getAllInfoBuilderList() {
        return getAllInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AllInfo, AllInfo.Builder, AllInfoOrBuilder>
          getAllInfoFieldBuilder() {
        if (allInfoBuilder_ == null) {
          allInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AllInfo, AllInfo.Builder, AllInfoOrBuilder>(
                  allInfo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          allInfo_ = null;
        }
        return allInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:S2C_GetUserInfo)
    }

    // @@protoc_insertion_point(class_scope:S2C_GetUserInfo)
    private static final S2C_GetUserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new S2C_GetUserInfo();
    }

    public static S2C_GetUserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C_GetUserInfo>
        PARSER = new com.google.protobuf.AbstractParser<S2C_GetUserInfo>() {
      public S2C_GetUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2C_GetUserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_GetUserInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S2C_GetUserInfo> getParserForType() {
      return PARSER;
    }

    public S2C_GetUserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AllInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AllInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string bother = 1;</code>
     */
    String getBother();
    /**
     * <code>string bother = 1;</code>
     */
    com.google.protobuf.ByteString
        getBotherBytes();

    /**
     * <code>string father = 2;</code>
     */
    String getFather();
    /**
     * <code>string father = 2;</code>
     */
    com.google.protobuf.ByteString
        getFatherBytes();

    /**
     * <code>string mother = 3;</code>
     */
    String getMother();
    /**
     * <code>string mother = 3;</code>
     */
    com.google.protobuf.ByteString
        getMotherBytes();
  }
  /**
   * Protobuf type {@code AllInfo}
   */
  public  static final class AllInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AllInfo)
      AllInfoOrBuilder {
    // Use AllInfo.newBuilder() to construct.
    private AllInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AllInfo() {
      bother_ = "";
      father_ = "";
      mother_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AllInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              bother_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              father_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              mother_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ZLTest.internal_static_AllInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ZLTest.internal_static_AllInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AllInfo.class, Builder.class);
    }

    public static final int BOTHER_FIELD_NUMBER = 1;
    private volatile Object bother_;
    /**
     * <code>string bother = 1;</code>
     */
    public String getBother() {
      Object ref = bother_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bother_ = s;
        return s;
      }
    }
    /**
     * <code>string bother = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBotherBytes() {
      Object ref = bother_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bother_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FATHER_FIELD_NUMBER = 2;
    private volatile Object father_;
    /**
     * <code>string father = 2;</code>
     */
    public String getFather() {
      Object ref = father_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        father_ = s;
        return s;
      }
    }
    /**
     * <code>string father = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFatherBytes() {
      Object ref = father_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        father_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOTHER_FIELD_NUMBER = 3;
    private volatile Object mother_;
    /**
     * <code>string mother = 3;</code>
     */
    public String getMother() {
      Object ref = mother_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mother_ = s;
        return s;
      }
    }
    /**
     * <code>string mother = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMotherBytes() {
      Object ref = mother_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mother_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBotherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bother_);
      }
      if (!getFatherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, father_);
      }
      if (!getMotherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mother_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBotherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bother_);
      }
      if (!getFatherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, father_);
      }
      if (!getMotherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mother_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AllInfo)) {
        return super.equals(obj);
      }
      AllInfo other = (AllInfo) obj;

      boolean result = true;
      result = result && getBother()
          .equals(other.getBother());
      result = result && getFather()
          .equals(other.getFather());
      result = result && getMother()
          .equals(other.getMother());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOTHER_FIELD_NUMBER;
      hash = (53 * hash) + getBother().hashCode();
      hash = (37 * hash) + FATHER_FIELD_NUMBER;
      hash = (53 * hash) + getFather().hashCode();
      hash = (37 * hash) + MOTHER_FIELD_NUMBER;
      hash = (53 * hash) + getMother().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AllInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AllInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AllInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AllInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AllInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AllInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AllInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AllInfo)
        AllInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ZLTest.internal_static_AllInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ZLTest.internal_static_AllInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AllInfo.class, Builder.class);
      }

      // Construct using com.zl.third.brother.utils.netty.protobuf.ZLTest.AllInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bother_ = "";

        father_ = "";

        mother_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ZLTest.internal_static_AllInfo_descriptor;
      }

      public AllInfo getDefaultInstanceForType() {
        return AllInfo.getDefaultInstance();
      }

      public AllInfo build() {
        AllInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AllInfo buildPartial() {
        AllInfo result = new AllInfo(this);
        result.bother_ = bother_;
        result.father_ = father_;
        result.mother_ = mother_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AllInfo) {
          return mergeFrom((AllInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AllInfo other) {
        if (other == AllInfo.getDefaultInstance()) return this;
        if (!other.getBother().isEmpty()) {
          bother_ = other.bother_;
          onChanged();
        }
        if (!other.getFather().isEmpty()) {
          father_ = other.father_;
          onChanged();
        }
        if (!other.getMother().isEmpty()) {
          mother_ = other.mother_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AllInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AllInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object bother_ = "";
      /**
       * <code>string bother = 1;</code>
       */
      public String getBother() {
        Object ref = bother_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bother_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string bother = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBotherBytes() {
        Object ref = bother_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bother_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bother = 1;</code>
       */
      public Builder setBother(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bother_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bother = 1;</code>
       */
      public Builder clearBother() {
        
        bother_ = getDefaultInstance().getBother();
        onChanged();
        return this;
      }
      /**
       * <code>string bother = 1;</code>
       */
      public Builder setBotherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bother_ = value;
        onChanged();
        return this;
      }

      private Object father_ = "";
      /**
       * <code>string father = 2;</code>
       */
      public String getFather() {
        Object ref = father_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          father_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string father = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFatherBytes() {
        Object ref = father_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          father_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string father = 2;</code>
       */
      public Builder setFather(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        father_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string father = 2;</code>
       */
      public Builder clearFather() {
        
        father_ = getDefaultInstance().getFather();
        onChanged();
        return this;
      }
      /**
       * <code>string father = 2;</code>
       */
      public Builder setFatherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        father_ = value;
        onChanged();
        return this;
      }

      private Object mother_ = "";
      /**
       * <code>string mother = 3;</code>
       */
      public String getMother() {
        Object ref = mother_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mother_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mother = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMotherBytes() {
        Object ref = mother_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mother_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mother = 3;</code>
       */
      public Builder setMother(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mother_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mother = 3;</code>
       */
      public Builder clearMother() {
        
        mother_ = getDefaultInstance().getMother();
        onChanged();
        return this;
      }
      /**
       * <code>string mother = 3;</code>
       */
      public Builder setMotherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mother_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AllInfo)
    }

    // @@protoc_insertion_point(class_scope:AllInfo)
    private static final AllInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AllInfo();
    }

    public static AllInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllInfo>
        PARSER = new com.google.protobuf.AbstractParser<AllInfo>() {
      public AllInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AllInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AllInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AllInfo> getParserForType() {
      return PARSER;
    }

    public AllInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_GetUserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2S_GetUserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_GetUserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_S2C_GetUserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014ZLTest.proto\032\020ZLBaseTest.proto\"f\n\017C2S_" +
      "GetUserInfo\022\016\n\006userId\030\001 \001(\005\022\017\n\007content\030\002" +
      " \001(\t\022\027\n\004info\030\003 \001(\0132\t.TsetInfo\022\031\n\007allInfo" +
      "\030\004 \003(\0132\010.AllInfo\"`\n\017S2C_GetUserInfo\022\014\n\004n" +
      "ame\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\027\n\004info\030\003 \001(\0132\t.T" +
      "setInfo\022\031\n\007allInfo\030\004 \003(\0132\010.AllInfo\"9\n\007Al" +
      "lInfo\022\016\n\006bother\030\001 \001(\t\022\016\n\006father\030\002 \001(\t\022\016\n" +
      "\006mother\030\003 \001(\t*D\n\nE_ALL_TEST\022\020\n\014ALL_TEST_" +
      "ONE\020\000\022\020\n\014ALL_TEST_TWO\020\001\022\022\n\016ALL_TEST_THRE" +
      "E\020\002B3\n)com.zl.third.brother.utils.netty.",
      "protobufB\006ZLTestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ZLBaseTest.getDescriptor(),
        }, assigner);
    internal_static_C2S_GetUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C2S_GetUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2S_GetUserInfo_descriptor,
        new String[] { "UserId", "Content", "Info", "AllInfo", });
    internal_static_S2C_GetUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_S2C_GetUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_S2C_GetUserInfo_descriptor,
        new String[] { "Name", "Age", "Info", "AllInfo", });
    internal_static_AllInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AllInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllInfo_descriptor,
        new String[] { "Bother", "Father", "Mother", });
    ZLBaseTest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
